### ISSUE TITLE
Adoption of Charter

### ISSUE THREAD

**Issue by annabelleee** [archesproject/ARM_Working_Group#11]
Vote on the adoption of the Arches Resource Model Working Group Charter:
https://docs.google.com/document/d/1OCvy8x9TGQJ1wyOzIPKO_HjfgS5vWk-wEop1ze_LC3w/edit

As a reminder, please vote as follows:
+1 - Yes/Agree
0 - Neutral
-1 - No/Disagree

If you are a -1, please state why and we can address this at the next meeting.

**Comment by azaroth42** [comment]
+1

**Comment by adamlodge** [comment]
+1

**Comment by dwuthrich** [comment]
+1

**Comment by workergnome** [comment]
+1

**Comment by Philbox** [comment]
+1

**Comment by Habennin** [comment]
+1

**Comment by annabelleee** [comment]
+1 from me, so the charter has been adopted unanimously on March 20, 2018.
